x-common-env: &cenv
  MEILI_URL: http://search:7700
  MEILI_MASTER_KEY: vODkljPcfFANYNepCHyDyGjzAMPcdHnrb6X5KyXQPWo

services:
  web:
    cap_drop: [ALL]
    container_name: wanderer-web
    image: web-local:latest
    networks: [web-to-external, internal-network]
    ports: [3000:3000]
    read_only: true
    restart: unless-stopped
    volumes: [./data/uploads:/app/uploads]
    depends_on:
      db: { condition: service_healthy }
      search: { condition: service_healthy }
    environment:
      <<: *cenv
      BODY_SIZE_LIMIT: Infinity
      ORIGIN: http://localhost:3000
      PUBLIC_DISABLE_SIGNUP: "false"
      PUBLIC_NOMINATIM_URL: https://nominatim.openstreetmap.org
      PUBLIC_OVERPASS_API_URL: https://overpass-api.de
      PUBLIC_POCKETBASE_URL: http://db:8090
      PUBLIC_VALHALLA_URL: https://valhalla1.openstreetmap.de
      UPLOAD_FOLDER: /app/uploads
      UPLOAD_PASSWORD:
      UPLOAD_USER:
    healthcheck:
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
      test: ["CMD", "/curl", "--fail", "http://localhost:3000"]

  search:
    cap_drop: [ALL]
    container_name: wanderer-search
    image: getmeili/meilisearch:v1.11.3
    networks: [internal-network]
    ports: [7700]
    restart: unless-stopped
    volumes: [./data/data.ms:/meili_data/data.ms]
    environment:
      <<: *cenv
      MEILI_NO_ANALYTICS: "true"
    healthcheck:
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
      test: ["CMD", "/usr/bin/curl", "--fail", "http://localhost:7700/health"]

  db:
    cap_drop: [ALL]
    container_name: wanderer-db
    depends_on: { search: { condition: service_healthy } }
    image: db-local:latest
    networks: [internal-network]
    ports: [8090]
    read_only: true
    restart: unless-stopped
    volumes: [./data/pb_data:/pb_data]
    environment:
      <<: *cenv
      ORIGIN: http://localhost:3000
    healthcheck:
      interval: 15s
      retries: 10
      start_period: 20s
      timeout: 10s
      test: ["CMD", "/curl", "--fail", "http://localhost:8090/health"]

networks:
  web-to-external:
    internal: false
    attachable: false
    driver: bridge
  internal-network:
    internal: true
    attachable: false
    driver: bridge
