blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¡ Feature request"
    url: https://github.com/open-wanderer/wanderer/discussions/new?category=ideas
    about: Suggest an idea for this project.
  - name: "â“ Ask a question"
    url: https://github.com/open-wanderer/wanderer/discussions/new?category=q-a
    about: Please ask and answer questions here.